Some things to get done

* TODO Embed help as files in the binary?
  Here is a good link on how to do this:
  http://www.linuxjournal.com/content/embedding-file-executable-aka-hello-world-version-5967
* TODO Convert the heightmap into an integer based heightmap.
  This will save space.
* TODO Persist heightmap to disk into a world directory.
* TODO Wire an ui transition to a command object without any callback assigned.
  This makes it possible to do cmd to ui state without a callback with a single
  function call to execute the state change.

  It could be usefull for the cb function to be able to abort the change due to
  some error as well. Or we might wanna assign a cb to the transition object
  instead that checks if the transition is allowed or not.

  We could also provide the state machine with a check that tests each for illegal
  ui state operations.

  Move the transition declaration to the file where the call to d_ui_do_transition
  is done.
* DONE Place menu of list of commands where you want.
  Today this is always rendered at the center of the screen. This should be changed.
* TODO Create the .dungeons home directory when starting the application.
  .dungeons/worlds/my_world/
  .dungeons/dungeons.conf
